
version: '3.8'
services:
  # redis_db:
  #   image: "redis:alpine"
  #   command: ["redis-server", "--bind", "redis", "--port", "6379"]
  #   ports:
  #     - 6379:6379
  #   extra_hosts:
  #       - "host.docker.internal:host-gateway"
  #   volumes:
  #     - redis_data:/data
  #   restart: always
  #   environment:
  #     - REDIS_REPLICATION_MODE=master

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=teste123
    ports:
      - 8082:8081
    extra_hosts:
        - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  nx-ms-greeting:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/microservices/ms-greeting/Dockerfile
      target: development
    depends_on:
      - redis
    environment:
      - REDIS_URL="redis://host.docker.internal:6379"
    ports:
      - 5001:5001
    extra_hosts:
        - "host.docker.internal:host-gateway"
        - localhost:192.168.100.231
    expose:
      - "6379"
    links:
      - redis
    restart: on-failure
    volumes:
      - .:/app
      - ms-ms-greeting_vol:/usr/src/ms-greeting/
      - node_modules:/usr/src/node_modules/
    networks:
      - monorepo_net

  nx-bot-whatsapp:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/bots/api-whatsapp/Dockerfile
      target: development
    depends_on:
      - redis
    environment:
      - REDIS_URL="redis://host.docker.internal:6379"
    ports:
      - 4001:4001
    links:
      - redis
    restart: on-failure
    volumes:
      - .:/app
      - api-bot-whatsapp_vol:/usr/src/bot-api-whatsapp/
      - node_modules:/usr/src/node_modules/
    networks:
      - monorepo_net

  nx-bot-telegram:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/bots/api-telegram/Dockerfile
      target: development
    depends_on:
      - redis
    environment:
      - REDIS_URL="redis://host.docker.internal:6379"
    ports:
      - 6001:6001
    links:
      - redis
    restart: on-failure
    volumes:
      - .:/app
      - api-bot-telegram_vol:/usr/src/bot-api-telegram/
      - node_modules:/usr/src/node_modules/
    networks:
      - monorepo_net

  nx-chatclass:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/api-chat-class/Dockerfile
      target: development
    env_file: env.dev
    depends_on:
      - redis
    environment:
      - REDIS_URL="redis://host.docker.internal:6379"
    ports:
      - 3001:3001
    extra_hosts:
        - "host.docker.internal:host-gateway"
        - localhost:192.168.100.231
    links:
      - redis
    restart: on-failure
    volumes:
      - .:/app
      - api-chatclass_vol:/usr/src/api-chat-class/
      - node_modules:/usr/src/node_modules/
    networks:
      - monorepo_net

volumes:
  api-chatclass_vol:
  api-bot-whatsapp_vol:
  api-bot-telegram_vol:
  ms-ms-greeting_vol:
  node_modules:
  postgres_data:
  redis_data:

networks:
  monorepo_net:
    driver: bridge

