
version: '3.8'
services:
  nx-chatclass:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/api-chat-class/Dockerfile
      target: development
    env_file: env.dev
    environment:
     - VAR_C=C
     - VAR_D=D
    ports:
      - 3001:3001
    restart: on-failure
    volumes:
      - .:/app
      - api-chatclass_vol:/usr/src/api-chat-class/
      - node_modules:/usr/src/api-chat-class/node_modules/
    networks:
      - monorepo_net
  nx-bot-whatsapp:
    build:
      context: .
      dockerfile: /home/duard/zdev/chatclass-org/apps/bots/api-whatsapp/Dockerfile
      target: development
    environment:
     - VAR_C=C
     - VAR_D=D
    ports:
      - 4001:4001
    restart: on-failure
    volumes:
      - .:/app
      - api-bot-whatsapp_vol:/usr/src/bot-api-whatsapp/
      - node_modules:/usr/src/bot-api-whatsapp/node_modules/
    networks:
      - monorepo_net

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kiwi
      POSTGRES_USER: _username_
      POSTGRES_PASSWORD: _password_
    volumes:
      - postgres_data:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  # ./usr/src/api-chat-class/:
  # ./usr/src/bot-api-whatsapp/:
  api-chatclass_vol:
  api-bot-whatsapp_vol:
  node_modules:
  postgres_data:
  redis_data:

networks:
  monorepo_net:
    driver: bridge


